### PR TITLE
Add --media-type and --media-pos arguments for raster format

### PR DESCRIPTION
**Pull request by jameshalsall**

### CODE REVIEW

**Comment by attah** [comment]
I took at stab at an implementation more in line with how i'd want it to work.
Please take a look: https://github.com/attah/ppm2pwg/pull/15
I think i'd want to test on an some actual printers before merging - and if you do that, please share the results.

**Comment by jameshalsall** [comment]
Context for this change: we are currently printing via CUPS but are looking to bypass it and talk directly with printers.

> And i'm curious; how did you figure out it was necessary for your use-case? I've always felt it weird to duplicate things from IPP to the raster headers en-masse (but that is semi-officially the way to go).

From my early testing I found our particular printers to respect PWG header options better than IPP's standard attributes, so we are looking to embed options in the PWG wherever there is support for it in the raster format (using https://ftp.pwg.org/pub/pwg/candidates/cs-ippraster10-20120420-5102.4.pdf as a guide)

> Probably by means of EnumSwitchArg, though i need to do some thinking on not duplicating the enum definition, or at least not needing to write code for mapping two enums with the same definition as was fine for previous smaller enums.
> [...]
> Injecting code into another class, while a pretty good place to have it, is quite surprising. And putting in the wrong files compared to the class is simply not ok. Sorry.

Yeah I really didn't like my unordered map implementation for validation as it just duplicates what's in the codable, but this is my first time writing C++ so I wasn't sure how to make use of the ENUMs embedded in the codable. Also not surprising I placed things in the wrong places :)

> Is there a specific need for the case-insensitivity that i should be aware of?

Not particularly, I was just implementing it the most user-friendly way possible, and it felt like entering case sensitive values was more fiddly for the user.

> BTW, i was trying to get hold of your colleague Dave Cole a few weeks back, just to give you guys a heads-up that the IPP client from SeaPrint is moving to this repo, and standard C++. It looked like you had just started looking at another client then. Mine will probably never be the greatest, especially when not used from within C++, but it will have one "killer feature" in that it can sync and divide the options between IPP and the raster processing, according to printer capabilities.

Very nice, we use our own client which has a lot of other functionality other than just spooling but it would be very interesting to see your implementation on the IPP/raster options division!

**Comment by attah** [comment]
> Context for this change: we are currently printing via CUPS but are looking to bypass it and talk directly with printers.

Your colleague told me as much... sounds like a good idea.
(No need to rebase his changes though, stdin/stdout support is all done)

> as it just duplicates what's in the codable, but this is my first time writing C++ so I wasn't sure how to make use of the ENUMs embedded in the codable. Also not surprising I placed things in the wrong places :)

In your defense, Codable (and ArgGet is all stuff i have made just for this project, with just about zero documentation.

>  I was just implementing it the most user-friendly way possible, and it felt like entering case sensitive values was more fiddly for the user.

I think i'll just go all hyphenated lowercase then for now (for both), matching how media-type registrations look here: https://www.pwg.org/ipp/ipp-registrations.xml

**Comment by attah** [comment]
Fixed by https://github.com/attah/ppm2pwg/pull/15

**Pull request closed without merging**
